Repository sonata-project/SonataNotificationBundle, pull requests merged in 2018-02, with the labels that each got.

#315 Commands as services
  src/DependencyInjection/SonataNotificationExtension.php
  src/Resources/config/command.xml
Labels: patch

#307 using each() is deprecated since PHP 7.2
  src/Backend/PostponeRuntimeBackend.php
Labels: patch

#317 Remove compatibility with FOSRest < 2.1
  composer.json
  src/Controller/Api/MessageController.php
  tests/Controller/Api/MessageControllerTest.php
Labels: minor

#318 Make services public
  src/Resources/config/backend.xml
Labels: patch

#319 Minor composer improvements
  composer.json
Labels: pedantic
