Repository sonata-project/SonataNotificationBundle, pull requests merged in 2020-02, with the labels that each got.

#416 Address event dispatcher deprecations
  composer.json
  src/Backend/AMQPBackend.php
  src/Backend/MessageManagerBackend.php
  src/Backend/RuntimeBackend.php
  src/Command/ConsumerHandlerCommand.php
  src/Command/RestartCommand.php
  src/Consumer/ConsumerEvent.php
  src/Event/IterateEvent.php
  tests/Backend/PostponeRuntimeBackendTest.php
Labels: pedantic

#414 Remove SonataEasyExtendsBundle
  composer.json
  docs/reference/advanced_configuration.rst
  docs/reference/installation.rst
  src/DependencyInjection/Configuration.php
  src/DependencyInjection/SonataNotificationExtension.php
  src/Resources/config/doctrine/Message.orm.xml.skeleton
Labels: minor

#422 Fix doctrine deprecations
  composer.json
  src/Event/DoctrineBackendOptimizeListener.php
  src/Event/DoctrineOptimizeListener.php
  tests/Event/DoctrineOptimizeListenerTest.php
Labels: patch
